[tasks.build]
description = "Build complete Binoxxo into dist"
dependencies = [
    "build_wasm",
    "build_css",
    "build_assets"
]

[tasks.build_wasm]
description = "Build with wasm-pack"
install_crate = "wasm-pack"
command = "wasm-pack"
args = ["build", "--target", "no-modules", "--out-name", "binoxxo_webapp_seed", "--out-dir", "./dist", "--release"]

[tasks.build_css]
description = "Build css from sass template"
install_crate = { crate_name = "rsass", binary = "rsass", features = ["commandline"], test_arg = "--help" }
script = [ "rsass ./assets/main.scss >./dist/main.css" ]

[tasks.build_assets]
description = "Copy assets into dist dir"
script = [
    '''
    cp assets/index.html ./dist
    cp assets/favicon.png ./dist
    cp -r assets/extra ./dist
    '''
]

[tasks.build_assets.windows]
description = "Copy assets into dist dir"
script = [
    '''
    copy assets\index.html .\dist
    copy assets\favicon.png .\dist
    xcopy assets\extra .\dist /E /Y
    '''
]

[tasks.serve]
description = "Start server for given example"
install_crate = { crate_name = "https", binary = "http", test_arg = "--help" }
workspace = false
command = "http"
args = ["./dist"]